import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-sqlite'

// Hand-written rather than generated by `migrate:create`: the schema
// snapshot that command diffs against hasn't been regenerated since
// 20260907_222600_minutes_submissions, so every migration since has been
// invisible to it — running it now asks unrelated, ambiguous
// rename-or-new questions about changes from other migrations. See
// DATABASE_MIGRATIONS.md for the plan to fix that. This migration's SQL was
// instead copied directly from the actual schema push mode already created
// locally for these two changes, confirmed column-for-column against the
// local sqlite file before being written here.
export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  // Pages: register the new "Form" layout block (published + versions tables)
  await db.run(sql`
    CREATE TABLE \`pages_blocks_form\` (
      \`_order\` integer NOT NULL,
      \`_parent_id\` integer NOT NULL,
      \`_path\` text NOT NULL,
      \`id\` text PRIMARY KEY NOT NULL,
      \`form_id\` integer,
      \`block_name\` text,
      FOREIGN KEY (\`form_id\`) REFERENCES \`forms\`(\`id\`) ON UPDATE no action ON DELETE set null,
      FOREIGN KEY (\`_parent_id\`) REFERENCES \`pages\`(\`id\`) ON UPDATE no action ON DELETE cascade
    );
  `)
  await db.run(
    sql`CREATE INDEX \`pages_blocks_form_order_idx\` ON \`pages_blocks_form\` (\`_order\`);`,
  )
  await db.run(
    sql`CREATE INDEX \`pages_blocks_form_parent_id_idx\` ON \`pages_blocks_form\` (\`_parent_id\`);`,
  )
  await db.run(
    sql`CREATE INDEX \`pages_blocks_form_path_idx\` ON \`pages_blocks_form\` (\`_path\`);`,
  )
  await db.run(
    sql`CREATE INDEX \`pages_blocks_form_form_idx\` ON \`pages_blocks_form\` (\`form_id\`);`,
  )

  await db.run(sql`
    CREATE TABLE \`_pages_v_blocks_form\` (
      \`_order\` integer NOT NULL,
      \`_parent_id\` integer NOT NULL,
      \`_path\` text NOT NULL,
      \`id\` integer PRIMARY KEY NOT NULL,
      \`form_id\` integer,
      \`_uuid\` text,
      \`block_name\` text,
      FOREIGN KEY (\`form_id\`) REFERENCES \`forms\`(\`id\`) ON UPDATE no action ON DELETE set null,
      FOREIGN KEY (\`_parent_id\`) REFERENCES \`_pages_v\`(\`id\`) ON UPDATE no action ON DELETE cascade
    );
  `)
  await db.run(
    sql`CREATE INDEX \`_pages_v_blocks_form_order_idx\` ON \`_pages_v_blocks_form\` (\`_order\`);`,
  )
  await db.run(
    sql`CREATE INDEX \`_pages_v_blocks_form_parent_id_idx\` ON \`_pages_v_blocks_form\` (\`_parent_id\`);`,
  )
  await db.run(
    sql`CREATE INDEX \`_pages_v_blocks_form_path_idx\` ON \`_pages_v_blocks_form\` (\`_path\`);`,
  )
  await db.run(
    sql`CREATE INDEX \`_pages_v_blocks_form_form_idx\` ON \`_pages_v_blocks_form\` (\`form_id\`);`,
  )

  // Photo Grid (3-Wide): new optional "Courtesy of" credit on each photo,
  // across every context the block can appear in (Pages + its versions
  // table, Candidates, and the shared Candidate Pages global).
  await db.run(sql`ALTER TABLE \`pages_blocks_media_grid_items\` ADD \`credit\` text;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_media_grid_items\` ADD \`credit\` text;`)
  await db.run(sql`ALTER TABLE \`candidates_blocks_media_grid_items\` ADD \`credit\` text;`)
  await db.run(sql`ALTER TABLE \`candidate_pages_blocks_media_grid_items\` ADD \`credit\` text;`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.run(sql`ALTER TABLE \`candidate_pages_blocks_media_grid_items\` DROP COLUMN \`credit\`;`)
  await db.run(sql`ALTER TABLE \`candidates_blocks_media_grid_items\` DROP COLUMN \`credit\`;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_media_grid_items\` DROP COLUMN \`credit\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_media_grid_items\` DROP COLUMN \`credit\`;`)

  await db.run(sql`DROP TABLE \`_pages_v_blocks_form\`;`)
  await db.run(sql`DROP TABLE \`pages_blocks_form\`;`)
}
